import { DashboardShell } from "@/components/dashboard-shell";
import { EventLogFilters } from "@/components/event-log-filters";
import { StatusBadge } from "@/components/status-badge";
import { SyncJobRetryButton } from "@/components/sync-job-retry-button";
import { requireUser } from "@/lib/auth";
import { supabaseAdmin } from "@/lib/db/server";

export default async function WorkersPage({ searchParams }: { searchParams: Promise<{ status?: string; eventType?: string }> }) {
  const user = await requireUser(); const params = await searchParams;
  const { data: recentJobs } = await supabaseAdmin.from("publish_jobs").select("id, platform, status, attempts, failure_reason, created_at, updated_at").eq("user_id", user.id).order("updated_at", { ascending: false }).limit(30);
  const { data: syncJobs } = await supabaseAdmin.from("sync_jobs").select("id, provider, job_type, status, attempts, failure_reason, updated_at").eq("user_id", user.id).order("updated_at", { ascending: false }).limit(30);
  const { data: importRuns } = await supabaseAdmin.from("import_runs").select("id, provider, entity_type, imported_count, skipped_count, failed_count, created_at").eq("user_id", user.id).order("created_at", { ascending: false }).limit(30);
  let eventsQuery = supabaseAdmin.from("event_logs").select("id, event_type, status, message, created_at").eq("user_id", user.id).order("created_at", { ascending: false }).limit(30);
  if (params.status) eventsQuery = eventsQuery.eq("status", params.status);
  if (params.eventType) eventsQuery = eventsQuery.ilike("event_type", `%${params.eventType}%`);
  const { data: events } = await eventsQuery;
  return <DashboardShell><div className="space-y-8"><div><h2 className="text-3xl font-bold">Workers</h2><p className="text-neutral-500">Monitor background processing and publish jobs.</p></div><div className="rounded-2xl border p-5 shadow-sm"><h3 className="text-lg font-semibold">Recent publish jobs</h3><div className="mt-4 space-y-3">{(recentJobs ?? []).length===0?<p className="text-sm text-neutral-500">No publish jobs yet.</p>:recentJobs?.map((job:any)=><div key={job.id} className="flex flex-wrap items-center justify-between gap-4 rounded-xl border p-3"><div><div className="font-medium">{job.platform}</div><div className="text-xs text-neutral-500">Attempts: {job.attempts} • Updated: {job.updated_at}</div>{job.failure_reason ? <div className="text-xs text-red-600">{job.failure_reason}</div> : null}</div><StatusBadge status={job.status} /></div>)}</div></div><div className="rounded-2xl border p-5 shadow-sm"><h3 className="text-lg font-semibold">Sync jobs</h3><div className="mt-4 space-y-3">{(syncJobs ?? []).length===0?<p className="text-sm text-neutral-500">No sync jobs yet.</p>:syncJobs?.map((job:any)=><div key={job.id} className="flex flex-wrap items-center justify-between gap-4 rounded-xl border p-3"><div><div className="font-medium">{job.provider} • {job.job_type}</div><div className="text-xs text-neutral-500">Attempts: {job.attempts} • Updated: {job.updated_at}</div>{job.failure_reason ? <div className="text-xs text-red-600">{job.failure_reason}</div> : null}</div><div className="flex items-center gap-2"><StatusBadge status={job.status} />{job.status === "failed" ? <SyncJobRetryButton syncJobId={job.id} /> : null}</div></div>)}</div></div><div className="rounded-2xl border p-5 shadow-sm"><h3 className="text-lg font-semibold">Import runs</h3><div className="mt-4 space-y-3">{(importRuns ?? []).length===0?<p className="text-sm text-neutral-500">No import runs yet.</p>:importRuns?.map((run:any)=><div key={run.id} className="rounded-xl border p-3"><div className="font-medium">{run.provider} • {run.entity_type}</div><div className="text-sm text-neutral-700">Imported: {run.imported_count} • Skipped: {run.skipped_count} • Failed: {run.failed_count}</div><div className="text-xs text-neutral-500">{run.created_at}</div></div>)}</div></div><div className="rounded-2xl border p-5 shadow-sm"><div className="flex flex-wrap items-center justify-between gap-4"><h3 className="text-lg font-semibold">Event log</h3><EventLogFilters /></div><div className="mt-4 space-y-3">{(events ?? []).length===0?<p className="text-sm text-neutral-500">No events yet.</p>:events?.map((event:any)=><div key={event.id} className="flex flex-wrap items-center justify-between gap-4 rounded-xl border p-3"><div><div className="font-medium">{event.event_type}</div><div className="text-sm text-neutral-700">{event.message}</div><div className="text-xs text-neutral-500">{event.created_at}</div></div><StatusBadge status={event.status} /></div>)}</div></div></div></DashboardShell>;
}
